# Generated by Django 5.0.6 on 2024-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_company_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_number",
                    models.CharField(default=None, max_length=15, null=True),
                ),
            ],
        ),
    ]
