# Generated by Django 5.0.6 on 2025-02-03 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="If balance > 0, customer owes you money; if balance < 0, you owe customer.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="distribution",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="If balance > 0, customer owes you money; if balance < 0, you owe customer.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distribution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
