# Generated by Django 5.0.6 on 2025-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_balance_customer_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="balance",
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="If balance > 0, customer owes you money; if balance < 0, you owe customer.",
                max_digits=10,
            ),
        ),
    ]
