# Generated by Django 5.0.6 on 2024-07-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="desctiption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="distribution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.distribution",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="formula",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.formula",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="per_pack",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="price_per_unit",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("TAB", "Tablets"),
                    ("SYP", "Syrup"),
                    ("CR", "Cream"),
                    ("CAP", "Capsule"),
                    ("INJ", "Injection"),
                    ("DRO", "Drops"),
                    ("DRI", "Drips"),
                    ("SEC", "Sechet"),
                    ("OTH", "Others"),
                ],
                default="TAB",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
