# Generated by Django 5.0.6 on 2024-07-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desctiption",
            new_name="description",
        ),
    ]
