# Generated by Django 5.0.6 on 2024-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_customer_id_order_customer_order_stocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
    ]
