# Generated by Django 5.0.6 on 2024-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_order_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="stock",
            name="price_per_unit",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("TAB", "Tablets"),
                    ("SYP", "Syrup"),
                    ("CREAM", "Cream"),
                    ("CAP", "Capsule"),
                    ("INJ", "Injection"),
                    ("DROPS", "Drops"),
                    ("DRIP", "Drips"),
                    ("SECHET", "Sechet"),
                    ("SAOP", "Saop"),
                    ("T/PASTE", "T/Paste"),
                    ("OINTMENT", "Ointment"),
                    ("LOTION", "Lotion"),
                    ("OTH", "Others"),
                ],
                max_length=10,
            ),
        ),
    ]
