# Generated by Django 5.0.6 on 2024-12-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_product_price_per_unit_stock_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_after_disc",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=99999),
            preserve_default=False,
        ),
    ]
