# Generated by Django 5.0.6 on 2024-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_order_total_after_disc_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_after_disc",
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
    ]
