# Generated by Django 5.0.6 on 2024-12-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer"),
        ("product", "0011_product_market_item_alter_order_total_after_disc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="bought_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock",
                to="core.distribution",
            ),
        ),
    ]
