# Generated by Django 5.0.6 on 2025-01-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_stock_perchase_price_alter_stock_price_per_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date"]},
        ),
    ]
