# Generated by Django 5.0.6 on 2025-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_stock_options_stock_barcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductProxy",
        ),
    ]
