# Generated by Django 5.0.6 on 2025-02-03 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_balance_customer_created_at_and_more"),
        ("product", "0017_delete_productproxy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="perchase_price",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_after_disc",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("TAB", "Tablets"),
                    ("SYP", "Syrup"),
                    ("CREAM", "Cream"),
                    ("CAP", "Capsule"),
                    ("INJ", "Injection"),
                    ("DROPS", "Drops"),
                    ("DRIP", "Drips"),
                    ("SECHET", "Sechet"),
                    ("SAOP", "Saop"),
                    ("T/PASTE", "T/Paste"),
                    ("OINTMENT", "Ointment"),
                    ("LOTION", "Lotion"),
                    ("B/CREAM", "B/Cream"),
                    ("INHALER", "INHALER"),
                    ("OTH", "Others"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="entry_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stockorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_orders",
                to="product.order",
            ),
        ),
        migrations.AlterField(
            model_name="stockorder",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_orders",
                to="product.stock",
            ),
        ),
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment_received", "Payment Received"),
                            ("payment_made", "Payment Made"),
                        ],
                        help_text="Type of transaction (e.g., payment received, payment made).",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.distribution",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_transactions",
                        to="product.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment_received", "Payment Received"),
                            ("payment_made", "Payment Made"),
                        ],
                        help_text="Type of transaction (e.g., payment received, payment made).",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.distribution",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_transactions",
                        to="product.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryDiscrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("home_expense", "Home Expense"),
                            ("free", "Free"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("expired", "Expired"),
                            ("donated", "Donated"),
                            ("returned_shortExpiry", "Returned Short Expiry"),
                            ("recovered_cash_approval", "Recovered Cash Approval"),
                        ],
                        help_text="Type of discrepancy (e.g., lost, expired, recovered, etc.).",
                        max_length=25,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount recovered in cash, if applicable.",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantity of stock affected by the discrepancy (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the discrepancy.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Distribution related to the product of the stock (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_discrepancies",
                        to="core.distribution",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded the discrepancy.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stock item related to the discrepancy (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancies",
                        to="product.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory Discrepancies",
                "ordering": ["-created_at"],
            },
        ),
    ]
