# Generated by Django 5.0.6 on 2025-02-03 15:08

import django.db.models.deletion
import pharmacy.product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_alter_order_options_remove_order_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded the stocks.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                validators=[pharmacy.product.models.validate_code128],
            ),
        ),
    ]
