# Generated by Django 5.0.6 on 2025-02-06 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_balance_customer_created_at_and_more"),
        ("product", "0019_stock_added_by_alter_stock_barcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["barcode"], name="product_sto_barcode_5d0c4d_idx"
            ),
        ),
    ]
